# Generated by Django 5.0.6 on 2026-05-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=120)),
                ('billing_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('ESSENTIAL', 'Essential'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('max_registers', models.PositiveIntegerField(default=1)),
                ('max_locations', models.PositiveIntegerField(default=1)),
                ('max_staff', models.PositiveIntegerField(default=5)),
                ('has_kds', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_loyalty', models.BooleanField(default=False)),
                ('has_delivery', models.BooleanField(default=False)),
                ('has_api', models.BooleanField(default=False)),
                ('has_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KDS', 'Kitchen Display System'), ('RESERVATIONS', 'Reservations Module'), ('DELIVERY', 'Delivery Integration'), ('LOYALTY', 'Loyalty & CRM'), ('EXTRA_REGISTER', 'Additional Register'), ('EXTRA_LOCATION', 'Additional Location')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='subscriptions.organizationsubscription')),
            ],
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan'),
        ),
    ]
