# Generated by Django 5.0.6 on 2026-05-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('min_order', models.PositiveIntegerField(default=0, help_text='Min order value in cents')),
                ('delivery_fee', models.PositiveIntegerField(default=0, help_text='Fee in cents')),
                ('est_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery')], default='DINE_IN', max_length=20)),
                ('platform', models.CharField(choices=[('POS', 'In-Store POS'), ('ONLINE', 'Online Order'), ('UBER_EATS', 'Uber Eats'), ('DELIVEROO', 'Deliveroo'), ('JUST_EAT', 'Just Eat'), ('QR_CODE', 'QR Code Order')], default='POS', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('OUT', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('est_delivery', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('platform_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='orders.order')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tables.restauranttable')),
            ],
        ),
    ]
